export const product = [
  {
    ProductId: 1,
    Name: 'Product 1',
    Price: 100,
    Description: 'Product Description asdfji askdf kashdkjfh sadkjhf ksadkfj askdjfh aksjdhf kashdkjf лофывр лорфылво рлофывр лофыр афлдыов а',
    CategryId: 1,
    Img: './img/1.webp',
  },
  {
    ProductId: 2,
    Name: 'Product 2',
    Price: 200,
    Description: 'Product Description',
    CategryId: 1,
    Img: './img/1.webp',
  },
  {
    ProductId: 3,
    Name: 'Product 3',
    Price: 300,
    Description: 'Product Description',
    CategryId: 3,
    Img: './img/1.webp',
  },
  {
    ProductId: 4,
    Name: 'Product 4',
    Price: 400,
    CategryId: 1,
    Description: 'Product Description',
    Img: './img/1.webp',
  },
  {
    ProductId: 5,
    Name: 'Product 2',
    Price: 500,
    CategryId: 1,
    Description: 'Product Description',
    Img: './img/1.webp',
  },
  {
    ProductId: 6,
    Name: 'Product 3',
    Price: 600,
    CategryId: 3,
    Description: 'Product Description',
    Img: './img/1.webp',
  },
  {
    ProductId: 7,
    Name: 'Product 1',
    Price: 700,
    Description: 'Product Description',
    CategryId: 1,
    Img: './img/1.webp',
  },
  {
    ProductId: 8,
    Name: 'Product 2',
    Price: 800,
    Description: 'Product Description',
    CategryId: 1,
    Img: './img/1.webp',
  },
  {
    ProductId: 9,
    Name: 'Product 3',
    Description: 'Product Description',
    Price: 900,
    CategryId: 3,
    Img: './img/1.webp',
  },
  {
    ProductId: 10,
    Name: 'Product 3',
    Description: 'Product Description',
    Price: 1000,
    CategryId: 3,
    Img: './img/1.webp',
  },
];
